# Generated by Django 6.0.6 on 2026-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(max_length=500)),
                ('featured_image_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('pending_since', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField()),
                ('source_news_title', models.CharField(max_length=300)),
            ],
        ),
    ]
