# Generated by Django 6.0.6 on 2026-06-22 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('google_news_link', models.URLField()),
                ('resolved_article_url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('scraped_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('fetched', 'Fetched'), ('scraped', 'Scraped'), ('scrape_failed', 'Scrape Failed'), ('written', 'Written'), ('carried_over', 'Carried Over')], default='fetched', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('linked_blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost')),
            ],
        ),
    ]
